---
title: "Assignment 1b Backup"
author: "Cameryn Brock"
date: "2/15/2021"
output: html_document
---

### Goal: 

 - Quantify revenue from diverting food waste streams to generate renewable energy and compost.  

### Inputs: 

 - Number of employees measured in full time equivalents FTE
 
### Parameters: 

 - Number of months for accounting,
 - Tons of organic waste per fte per month, 
 - Compost generated per ton organic waste, 
 - MMBtu natural gas produced per ton organic waste,
 - Price per ton hauled,
 - Price per ton compost,
 - Price per MMBtu

### Outputs: 

 - Average Monthly Revenue
	
### Modules:


 - `calc_hauled`: Calculate total tonnage from a given FTE input per month
    - input: Number of employees measured in FTE
    - parameter: Tons of organic waste per FTE per month
    - output: Tons of organic waste per month
 - `calc_compost`: Calculate average production monthly volume (compost)
    - input: Tons of organic waste per month
    - parameter: compost generated per ton organic waste
    - output: Tons of compost per monnth
 - `calc_biogas`: Calculate average production monthly volume (biogas)
    - input: Tons of organic waste per month
    - parameter: MMBtu natural gas produced per ton organic waste
    - output: MMbtu of natural gas per month
 - `revenue_hauled`: Calculate average monthly revenue (hauling)
    - input: Total food waste tonnage from a given FTE input per month (calc_hauled)
    - parameter: Charge of haul per ton of food waste * Total food waste tonnage from a given FTE input per month (calc_hauled)
    - output: Total revenue of food waste hauling from a given FTE per month
 - `revenue_biogas`: Calculate average monthly revenue (biogas)
    - input: Average production monthly volume of biogas (calc_biogas)
    - parameter: Average production monthly volume of biogas in MMBTUs (calc_biogas) * 293.07107 kWh * Charge per kWh
    - outpu: Total revenue of average production monthly volume of biogas
 - `revenue_compost`: Calculate average monthly revenue (compost)
    - input: Average production monthly volume (compost)
    - parameter: Charge per ton of compost * Average production monthly volume (ton) of compost
    - output: Total revenue of average production monthly volume of compost
 - `summarize_revenue`: Summarize average monthly revenue
    - input:
    - parameter:
    - output

### Flow Diagram:
  - https://lucid.app/lucidchart/01dfa95c-ebc2-4d94-b1dd-4c81b0c22d89/edit?page=0_0#?folder_id=home&browser=icon
